@startuml
|Pandora Contract|
|Workers|

|Pandora Contract|
start
:∀ responses = accept}

partition cognitiveMining {
  start
  :updateWorkersList]
  :cognitiveJobStarted/
  fork
    :waitingForResponses;

    while (∃ timeOut) is (yes)
      :updateTimeEstimation/
      fork
        :waitingForResponses;
        detach
      fork again
        |Workers|
        start
        :provideTimeEstimation>
      end fork

      |Pandora Contract|
      if (timeEstimation is given | no of tires > N) then (timeout)
        :penaltyToWorker#2]
        :repeatLottery(inPart)|
        detach
      else (yes)
        :penaltyToWorker#3]
      endif
    endwhile (noTimeout)
  fork again
    |Workers|
    start
    :runModel]
    :uploadResults]
    :commitJob]
  end fork
}

|Pandora Contract|
partition validateCognition {
  stop
}
@enduml
