@startuml
|Pandora Contract|
|Initial Worker|

|Pandora Contract|
start

partition initialAppeal {
  :appealOpened/
  fork
    :waitingForResponses;
    detach
  fork again
    |Initial Worker|
    if (wantToAppeal?) then (yes)
      :putAdditionalStake;
      :makeInitialAppeal>
    else (no)
      :acceptValidation>
    endif
  end fork

  |Pandora Contract|
  repeat
    if (initialAppeal) then (yes)
    elseif (acceptedValidation) then (yes)
      :punishWorker(leaveABitOfStake);
      stop
    else (timeout)
      :punishWorker(removeStake & reputation);
      stop
    endif
  repeat while (stakeIsSufficient) is (no)
}

partition closedArbitrage {
  stop
}
@enduml
