@startuml
box "Client"
  actor "Client" as client
  participant "Client dApp" as dapp
  entity "Cognitive Contract" as cognitiveContract
end box

box "Data"
  actor "Data Provider" as provider
  participant "Provider App" as app
  entity "Data Entity Contract" as dataContract
  database "IPFS" as ipfs
end box

box "Pandora Network"
  collections "Worker Nodes" as workers
  collections "Validating Nodes" as validators
  collections "Arbitor Nodes" as arbitors
  collections "Governing Nodes" as governors
  control "Keras/TensorFlow" as nn
end box

box "Pandora Boxchain"
  entity "Main Contract" as theContract
  entity "Worker Contract" as workerContract
end box
@enduml
