@startuml
state "Main Contract" as main {
  state "Cognitive Work Initialization" as cwi
  state "Cognitive Work Lottery" as cwl
  state "Waiting Workers" as wait_wrk

  [*] --> cwi: client request
  cwi --> work: create
  cwl --> wait_wrk
  wait_wrk --> cwl: upon rejections\n& timeouts
}


state "Cognitive Work Contract" as work {
  state "Init" as work_init
  state "Waiting Results" as cognition
  state "Data Arbitrage" as data_arb
  state "Validation" as validation

  [*] --> work_init
  work_init --> cwl: callback
  work_init --> cognition
  cwl --> cognition: workers
 ' cognition --> cwl: upon rejections\nand timeouts
  cognition --> validation: upon all results\nare collected
  cognition --> data_arb: incorrect\ndata\nreported
}


state "Initial Worker Contract" as worker {
  state "Idle" as idle
  state "Won Lottery" as won
  state "Checking Data" as checking
  state "Cognitive Work" as working
  state "Under Validation" as validating
  state "True Node" as true
  state "False Node" as false
  state "Appealing" as appealing
  state "Under Investigation" as investigation

  [*] --> idle
  cwl --> won: to winner nodes

  won --> checking: downloads\nand checks data
  won --> wait_wrk: busy (=reject)
  won --> idle: if rejected
  won --> [*]: went offline
  checking --> wait_wrk: accept
  checking --> cognition: incorrect data
  checking --> working: data are ok
  working --> validating: results are submitted
  working --> cognition: results
  validating --> true: results are correct
  true --> idle: return to base
  validating --> false: results are incorrect
  false --> idle: accepted or timeouted
  false --> appealing: decided to appeal
  appealing --> investigation
  investigation --> true
  investigation --> false
}
@enduml
