@startuml
'left to right direction
skinparam packageStyle rectangle

title Pandora Boxchain Data Entities Use Cases

actor :Generic Provider: as GP
actor :Kernel Provider: as KP
actor :Dataset Provider: as DP

GP --|> KP
GP --|> DP

rectangle "Data Entities" {
  usecase (Data Entity Creation) as newData
  usecase (Kernel Creation) as newKernel
  usecase (Dataset Creation) as newDataset
  usecase (Price Update) as priceUpdate

  newData ..> newKernel: include
  newData ..> newDataset: include
  priceUpdate .> newData: extend

  GP --- (priceUpdate): updates price
  KP -- (newKernel): provides data
  DP -- (newDataset): provides data
}
@enduml
