@startuml
skinparam packageStyle rectangle

title Pandora Boxchain Cognitive Work Use Cases

actor :Data Provider: as GP
actor :Kernel Provider: as KP
actor :Dataset Provider: as DP
actor :Client: as C
actor :Worker Node: as WN
actor :Validator Node: as VN1
actor :Arbiter Node: as VN2

KP <|-- GP: can be
DP <|-- GP: can be

VN1 <|-- VN2: higher reputation

rectangle "Cognitive Computing" {
  usecase (Cognitive Computing) as cognition
  usecase (Closed Arbitration) as closedArbitration
  usecase (Public Arbitration) as publicArbitration

  cognition ..> closedArbitration: extends
  closedArbitration ..> publicArbitration: extends
  (cognition) -- C: "init &\npayes\nfor work"
  WN -- (cognition): "performs\ncognitive\ncomputations\n& mines"
  WN -- (closedArbitration): initial\nappeal
  VN1 -- (cognition): "validates\ncomputation\nresults"
  VN2 -- (closedArbitration): "arbitrates &\n get rewards\nor penalties"
  (cognition) -- GP: got paid
  VN1 -- (publicArbitration): "arbitrates &\n get rewards\nor penalties"
  WN -- (publicArbitration): public\nappeal
  VN1 -- (publicArbitration): public\nappeal
}
@enduml
