@startuml
left to right direction
skinparam packageStyle rectangle

title Pandora Boxchain Actors Diagram

actor :Data Provider: as P
actor :Kernel Provider: as KP
actor :Dataset Provider: as DP
actor :Client: as C
actor :Working Node: as WN
actor :Validator Node: as VN1
actor :Arbiter Node: as VN2
actor :Governor Node: as GN

WN <|-- VN1: high stake
VN1 <|-- VN2: high reputation
VN2 <|-- GN: highest reputation

P <|-- KP
P <|-- DP
KP <|-l-|> DP: may be
KP <|-- C: may be
DP <|-- C: may be
@enduml
